name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image with commit SHA tag for multiple platforms
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          COMMIT_SHA=$(echo "${{ github.sha }}" | cut -c1-6)
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/${REPO_NAME}:${COMMIT_SHA} \
            --push .

      - name: Tag Docker image as latest for multiple platforms
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          COMMIT_SHA=$(echo "${{ github.sha }}" | cut -c1-6)
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/${REPO_NAME}:latest \
            --push .

      - name: Output Docker image URL
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          COMMIT_SHA=$(echo "${{ github.sha }}" | cut -c1-6)
          echo "Docker Image URL: ghcr.io/${REPO_NAME}:${COMMIT_SHA}"
          echo "Docker Image URL: ghcr.io/${REPO_NAME}:latest"
